[theme]
base = "dark"
primaryColor = "#3DA5FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"
font = "sans serif"

[server]
runOnSave = true
maxUploadSize = 1024

[browser]
gatherUsageStats = false
